// Server-generated fee receipt PDF — same pure-JS engine as the report card.
// Server-side only; import from route handlers.
import { Document, Page, Text, View, renderToBuffer } from "@react-pdf/renderer";

const C = {
  black: "#0A0A0F",
  blue: "#1A6BFF",
  cyan: "#00E5FF",
  grey: "#6B7280",
  line: "#E1E6EF",
  surface: "#F0F3F9",
  ink: "#15151D",
  success: "#00A576",
};

const L = {
  en: {
    title: "FEE PAYMENT RECEIPT",
    school: "School",
    student: "Student",
    className: "Class",
    date: "Date",
    method: "Payment method",
    reference: "Reference",
    amount: "Amount paid",
    status: "Status",
    confirmed: "CONFIRMED",
    generated: "Generated by EduTrack",
    demo: "Demo transaction. No real funds were moved.",
  },
  fr: {
    title: "REÇU DE PAIEMENT",
    school: "École",
    student: "Élève",
    className: "Classe",
    date: "Date",
    method: "Mode de paiement",
    reference: "Référence",
    amount: "Montant payé",
    status: "Statut",
    confirmed: "CONFIRMÉ",
    generated: "Généré par EduTrack",
    demo: "Transaction de démonstration. Aucun fonds réel transféré.",
  },
} as const;
export type ReceiptLang = keyof typeof L;

export type ReceiptPayload = {
  school: string;
  student: string;
  className: string;
  amountFcfa: number;
  method: string;
  reference: string;
  date: string; // YYYY-MM-DD
};

function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) {
  return (
    <View style={{ flexDirection: "row", justifyContent: "space-between", paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: C.line }}>
      <Text style={{ fontSize: 9, color: C.grey }}>{label}</Text>
      <Text style={{ fontSize: strong ? 12 : 10, fontFamily: "Helvetica-Bold", color: strong ? C.blue : C.ink }}>{value}</Text>
    </View>
  );
}

function ReceiptPdf({ data, lang }: { data: ReceiptPayload; lang: ReceiptLang }) {
  const t = L[lang];
  return (
    <Document title={`EduTrack Receipt ${data.reference}`} author="Flint Technologies">
      <Page size="A5" style={{ padding: 28, fontFamily: "Helvetica", fontSize: 10, color: C.ink }}>
        <View style={{ backgroundColor: C.black, borderRadius: 8, padding: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}>
          <View>
            <Text style={{ color: "#FFFFFF", fontSize: 16, fontFamily: "Helvetica-Bold" }}>EduTrack</Text>
            <Text style={{ color: C.cyan, fontSize: 6, letterSpacing: 2, marginTop: 2 }}>BY FLINT TECHNOLOGIES</Text>
          </View>
          <Text style={{ color: "#FFFFFF", fontSize: 9, fontFamily: "Helvetica-Bold" }}>{t.title}</Text>
        </View>

        <View style={{ marginTop: 16 }}>
          <Row label={t.school} value={data.school} />
          <Row label={t.student} value={`${data.student} · ${data.className}`} />
          <Row label={t.date} value={data.date} />
          <Row label={t.method} value={data.method} />
          <Row label={t.reference} value={data.reference} />
          <Row label={t.amount} value={`${data.amountFcfa.toLocaleString("en-US")} FCFA`} strong />
        </View>

        <View style={{ marginTop: 16, backgroundColor: C.surface, borderRadius: 6, padding: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}>
          <Text style={{ fontSize: 8, color: C.grey }}>{t.status}</Text>
          <Text style={{ fontSize: 10, fontFamily: "Helvetica-Bold", color: C.success }}>{t.confirmed}</Text>
        </View>

        <Text style={{ marginTop: 12, fontSize: 7, color: C.grey }}>{t.demo}</Text>

        <View style={{ position: "absolute", bottom: 20, left: 28, right: 28, borderTopWidth: 1, borderTopColor: C.line, paddingTop: 6, flexDirection: "row", justifyContent: "space-between" }} fixed>
          <Text style={{ fontSize: 7, color: C.grey }}>{t.generated} · flint-edu-track.vercel.app</Text>
          <Text style={{ fontSize: 7, color: C.grey }}>{data.reference}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function renderReceiptPdf(data: ReceiptPayload, lang: ReceiptLang): Promise<Buffer> {
  return renderToBuffer(<ReceiptPdf data={data} lang={lang} />);
}
