// Server-generated PDF report card (Phase 2 spec: real PDF, bilingual EN/FR).
// Pure-JS rendering via @react-pdf/renderer — no Chromium, Vercel-serverless safe.
// Only ever import this from route handlers / server code, never client components.
import { Document, Page, Text, View, renderToBuffer } from "@react-pdf/renderer";
import type { ReportPayload } from "@/lib/reportData";

const C = {
  black: "#0A0A0F",
  blue: "#1A6BFF",
  cyan: "#00E5FF",
  grey: "#6B7280",
  line: "#E1E6EF",
  surface: "#F0F3F9",
  ink: "#15151D",
  success: "#00A576",
  error: "#D93025",
};

const L = {
  en: {
    title: "STUDENT REPORT CARD",
    student: "Student",
    className: "Class",
    school: "School",
    region: "Region",
    attendance: "Attendance",
    subject: "Subject",
    seq1: "Sequence 1",
    seq2: "Sequence 2",
    average: "Average",
    overall: "Overall average",
    scale: "Scores are out of 20.",
    generated: "Generated by EduTrack",
    noGrades: "No grades recorded yet.",
  },
  fr: {
    title: "BULLETIN DE NOTES",
    student: "Élève",
    className: "Classe",
    school: "École",
    region: "Région",
    attendance: "Assiduité",
    subject: "Matière",
    seq1: "Séquence 1",
    seq2: "Séquence 2",
    average: "Moyenne",
    overall: "Moyenne générale",
    scale: "Notes sur 20.",
    generated: "Généré par EduTrack",
    noGrades: "Aucune note enregistrée.",
  },
} as const;
export type PdfLang = keyof typeof L;

const fmt = (n: number | null) => (n === null ? "—" : String(n));

function ReportCardPdf({ data, lang }: { data: ReportPayload; lang: PdfLang }) {
  const t = L[lang];
  const date = new Date().toISOString().slice(0, 10);
  return (
    <Document title={`EduTrack Report Card — ${data.studentName}`} author="Flint Technologies">
      <Page size="A4" style={{ padding: 36, fontFamily: "Helvetica", fontSize: 10, color: C.ink }}>
        {/* Masthead */}
        <View style={{ backgroundColor: C.black, borderRadius: 8, padding: 16, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}>
          <View>
            <Text style={{ color: "#FFFFFF", fontSize: 20, fontFamily: "Helvetica-Bold" }}>EduTrack</Text>
            <Text style={{ color: C.cyan, fontSize: 7, letterSpacing: 2, marginTop: 3 }}>BY FLINT TECHNOLOGIES</Text>
          </View>
          <Text style={{ color: "#FFFFFF", fontSize: 11, fontFamily: "Helvetica-Bold" }}>{t.title}</Text>
        </View>

        {/* Identity block */}
        <View style={{ flexDirection: "row", marginTop: 16, gap: 8 }}>
          {[
            [t.student, data.studentName],
            [t.className, data.className],
            [t.school, data.school],
            [t.region, data.region],
          ].map(([label, value]) => (
            <View key={label} style={{ flex: 1, backgroundColor: C.surface, borderRadius: 6, padding: 8 }}>
              <Text style={{ fontSize: 6.5, color: C.grey, letterSpacing: 1 }}>{String(label).toUpperCase()}</Text>
              <Text style={{ fontSize: 9.5, fontFamily: "Helvetica-Bold", marginTop: 3 }}>{value}</Text>
            </View>
          ))}
        </View>

        {/* Grades table */}
        <View style={{ marginTop: 18, borderWidth: 1, borderColor: C.line, borderRadius: 6 }}>
          <View style={{ flexDirection: "row", backgroundColor: C.black, borderTopLeftRadius: 5, borderTopRightRadius: 5, padding: 8 }}>
            <Text style={{ flex: 3, color: "#FFFFFF", fontFamily: "Helvetica-Bold", fontSize: 9 }}>{t.subject}</Text>
            <Text style={{ flex: 1, color: "#FFFFFF", fontFamily: "Helvetica-Bold", fontSize: 9, textAlign: "right" }}>{t.seq1}</Text>
            <Text style={{ flex: 1, color: "#FFFFFF", fontFamily: "Helvetica-Bold", fontSize: 9, textAlign: "right" }}>{t.seq2}</Text>
            <Text style={{ flex: 1, color: C.cyan, fontFamily: "Helvetica-Bold", fontSize: 9, textAlign: "right" }}>{t.average}</Text>
          </View>
          {data.subjects.length === 0 ? (
            <View style={{ padding: 14 }}>
              <Text style={{ color: C.grey }}>{t.noGrades}</Text>
            </View>
          ) : (
            data.subjects.map((s, i) => (
              <View
                key={s.subject}
                style={{ flexDirection: "row", padding: 8, backgroundColor: i % 2 ? C.surface : "#FFFFFF", borderTopWidth: 1, borderTopColor: C.line }}
              >
                <Text style={{ flex: 3 }}>{s.subject}</Text>
                <Text style={{ flex: 1, textAlign: "right" }}>{fmt(s.seq1)}</Text>
                <Text style={{ flex: 1, textAlign: "right" }}>{fmt(s.seq2)}</Text>
                <Text style={{ flex: 1, textAlign: "right", fontFamily: "Helvetica-Bold" }}>{fmt(s.avg)}</Text>
              </View>
            ))
          )}
        </View>

        {/* Summary row */}
        <View style={{ flexDirection: "row", marginTop: 12, gap: 8 }}>
          <View style={{ flex: 1, borderWidth: 1, borderColor: C.blue, borderRadius: 6, padding: 10 }}>
            <Text style={{ fontSize: 6.5, color: C.grey, letterSpacing: 1 }}>{t.overall.toUpperCase()}</Text>
            <Text style={{ fontSize: 16, fontFamily: "Helvetica-Bold", color: C.blue, marginTop: 3 }}>
              {data.overall === null ? "—" : `${data.overall} / 20`}
            </Text>
          </View>
          <View style={{ flex: 1, borderWidth: 1, borderColor: C.line, borderRadius: 6, padding: 10 }}>
            <Text style={{ fontSize: 6.5, color: C.grey, letterSpacing: 1 }}>{t.attendance.toUpperCase()}</Text>
            <Text
              style={{
                fontSize: 16,
                fontFamily: "Helvetica-Bold",
                marginTop: 3,
                color: data.attendanceRate !== null && data.attendanceRate < 80 ? C.error : C.success,
              }}
            >
              {data.attendanceRate === null ? "—" : `${data.attendanceRate}%`}
            </Text>
          </View>
        </View>

        <Text style={{ marginTop: 10, fontSize: 8, color: C.grey }}>{t.scale}</Text>

        {/* Footer */}
        <View
          style={{ position: "absolute", bottom: 28, left: 36, right: 36, borderTopWidth: 1, borderTopColor: C.line, paddingTop: 8, flexDirection: "row", justifyContent: "space-between" }}
          fixed
        >
          <Text style={{ fontSize: 7.5, color: C.grey }}>{t.generated} · flint-edu-track.vercel.app</Text>
          <Text style={{ fontSize: 7.5, color: C.grey }}>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function renderReportCardPdf(data: ReportPayload, lang: PdfLang): Promise<Buffer> {
  return renderToBuffer(<ReportCardPdf data={data} lang={lang} />);
}
